name: Update winget package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version number'
        required: true
        
      release-url:
        description: 'package release url, not required'
        required: true

jobs:
  wingetcreate-update:
    runs-on: windows-latest

    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Download & Run wingetcreate update
        shell: cmd
        run: |
          curl https://github.com/microsoft/winget-create/releases/latest/download/wingetcreate.exe -L
          wingetcreate.exe update -i ${{ secrets.PACKAGE_ID }} -u ${{ github.event.inputs.release-url }} -v ${{ github.event.inputs.version }}
# -t ${{ secrets.GH_TOKEN }}
